{% set name = "smoqe" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 836ada4f26d870188c513df86bc58ab58ba34ad82046131d02f72486d721240f

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - pymongo
    - docutils >=0.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - smoqe
  commands:
    - pip check

about:
  home: https://github.com/dangunter/smoqe
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Simplified MongoDB Query Expressions'

  description: |
    This module translates from a simple human-readable syntax into 
    a MongoDB query. Currently it does no execution of the query 
    -- use something like pymongo for that (as shown below).
  doc_url: https://github.com/dangunter/smoqe
  dev_url: https://github.com/dangunter/smoqe

extra:
  recipe-maintainers:
    - jan-janssen
