travis:
  secure:
    BINSTAR_TOKEN: JQ4PQ3OuNenCLD+PrLJAF9pw4atZlsa/kEwZpsaV5NDw4SoQACYmgtoRTfLha9fRvEfpuv6RW8xvG1fFCSxN0YeiG9V+gkoBQ04ullnhgygNjBlvEM9Lwn3Lp4FZ94bbA1aQj6PfkgYhm9dtsBhHNpsomfuViqxUjOmyPyo5KVKhM9vj7VmW8zPjhlSZbUuPJXUuiHtq7UgdnP+/1Yu64Nj0cmauwHwAmgkO/0wFMYlOH6cYouB15rD4cyV9rt1vGFlpjTVgg/o7TUa0rlIPab6gVh1q7tuTNFp6d4yo0MD87cdfkAGVw9BL0v8iwvV9SYoFKa88D89T934e2+7xiPMEtVcy3K0ASVeu1jZMvluBlV6t2OssUYKvkS/rfLVxbP1qwc2qpxxF7+5Yn6AZAVStrpie4sSYV4xdjUgEQnMM9hIJaasj28QHNS7npm9K3+/mdR/TF49hX1RtBpNo8f/aMTsvF71k+Uk7295r8F7VrWPwIxxtlk03Jz835Daqvdk7OgfjPBDtVzY5sSCiPQio4SD4Fluv8dx6WYrxjMnAmnB06FCLb3Cq1uxQiI7OXLVKk7vlRJ1lPUOoJ/QTIVUcOQ8LtrCRSzhdxew8rx1W2sAgKXkAckWLLMf8CzusRb7FHTdKNBMViYTel1/eN5xrpcD2H78+YQgQTRGCzyI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
